services:
  redis-main:
    image: redis:alpine
    container_name: valuator-main
    ports:
      - "6000:6379"
  redis-ru:
    image: redis:alpine
    container_name: valuator-ru
    ports:
      - "6001:6379"
  redis-eu:
    image: redis:alpine
    container_name: valuator-eu
    ports:
      - "6002:6379"
  redis-asia:
    image: redis:alpine
    container_name: valuator-asia
    ports:
      - "6003:6379"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
